SESSIONTOKEN: "TESTTOKEN2021"
EVENTNAME: "Test Event 2021"

LANG:
  PREFIX: "&8&l[&6&lMC&3&lSESSIFY&8&l]&r"
  NOTAUSER: "&cYou must be a user to be able to execute this command."
  NOUSERTOKEN: "&cNo token detected, provide a token to gain access [/verify TOKEN]."
  INCORRECTUSERTOKEN: "&cThe token that you have entered is incorrect, try again."
  CORRECTUSERTOKEN: "&aYou are now verified for the event %EVENTNAME%."
  USERALREADYVERIFIED: "&eYou are already verified."
  USERNOTVERIFIED: "&cYou are not verified, use /verify [TOKEN] to gain access."
  TOKENARGSOPTIONS: "&ePlease use one of the following /token [view/set]"
  TOKENCURRENT: "The current token is set to &b%TOKEN%"
  NONEWTOKEN: "&cYou cannot set an empty token, try again."
  NEWTOKENSET: "&aA new token has been set. Reload the server to take effect."