main: me.benrobson.mcsessify.MCSessifyMain
name: MCSessify
version: 1.0
author: Ben Robson
api-version: 1.17

commands:
  verify:
    description: Allows a player to verify themselves for access to Server.
    usage: /verify [token]
  token:
    description: Allows a Server Administrator view and set a new token.
    usage: /token [view/set]

permissions:
  mcsessify.verify:
    default: not op
  mcsessify.token:
    default: op